// Mocks generated by Mockito 5.4.6 from annotations
// in pet_finder_app/test/feature/home/presentation/cubit/cubit/home_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pet_finder_app/core/networking/api_result.dart' as _i3;
import 'package:pet_finder_app/feature/home/data/model/breed_model.dart' as _i6;
import 'package:pet_finder_app/feature/home/data/repo/home_repo.dart' as _i4;
import 'package:pet_finder_app/feature/home/data/services/home_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHomeService_0 extends _i1.SmartFake implements _i2.HomeService {
  _FakeHomeService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiResult_1<T> extends _i1.SmartFake implements _i3.ApiResult<T> {
  _FakeApiResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepo extends _i1.Mock implements _i4.HomeRepo {
  MockHomeRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeService get homeService =>
      (super.noSuchMethod(
            Invocation.getter(#homeService),
            returnValue: _FakeHomeService_0(
              this,
              Invocation.getter(#homeService),
            ),
          )
          as _i2.HomeService);

  @override
  _i5.Future<_i3.ApiResult<List<_i6.BreedModel>>> getBreeds({
    dynamic limit,
    dynamic page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBreeds, [], {#limit: limit, #page: page}),
            returnValue: _i5.Future<_i3.ApiResult<List<_i6.BreedModel>>>.value(
              _FakeApiResult_1<List<_i6.BreedModel>>(
                this,
                Invocation.method(#getBreeds, [], {#limit: limit, #page: page}),
              ),
            ),
          )
          as _i5.Future<_i3.ApiResult<List<_i6.BreedModel>>>);
}
