// Mocks generated by Mockito 5.4.6 from annotations
// in pet_finder_app/test/feature/home/data/repo/home_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pet_finder_app/feature/home/data/model/breed_model.dart' as _i4;
import 'package:pet_finder_app/feature/home/data/services/home_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HomeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeService extends _i1.Mock implements _i2.HomeService {
  MockHomeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.BreedModel>> getBreeds(int? limit, int? page) =>
      (super.noSuchMethod(
            Invocation.method(#getBreeds, [limit, page]),
            returnValue: _i3.Future<List<_i4.BreedModel>>.value(
              <_i4.BreedModel>[],
            ),
          )
          as _i3.Future<List<_i4.BreedModel>>);
}
